dist: xenial
language: csharp
solution: my-microting-base\Microting.MyMicrotingBase.sln
mono: none
dotnet: 3.1
addons:
  mariadb: '10.5'
script:
  - sudo mysql -e 'ALTER USER root@localhost IDENTIFIED VIA mysql_native_password'
  - dotnet restore
  - dotnet build Microting.MyMicrotingBase.sln
  - dotnet test -v n Microting.MyMicrotingBase.UnitTests/Microting.MyMicrotingBase.UnitTests.csproj
  - export GITVERSION=`git describe --abbrev=0 --tags | cut -d "v" -f 2`
  - echo $GITVERSION
  - dotnet pack Microting.MyMicrotingBase.sln -c Release -o ./artifacts -p:PackageVersion=$GITVERSION
  - export FILENAME="/home/travis/build/microting/my-microting-base/artifacts/Microting.MyMicrotingBase.${GITVERSION}.nupkg"
  - echo $FILENAME
  - dotnet nuget push $FILENAME -k $NUGET_SECRET_KEY -s https://api.nuget.org/v3/index.json || true